name: CMake Build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        working-directory: build/tests/
        run: ctest --output-on-failure
